[package]
name = "coco"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["coco-sys"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coco-sys = { path="./coco-sys" }